### ISSUE TITLE
Add field for link to OER repository (skillscommons.org)

### ISSUE THREAD

**Issue by billymeinke** [jkhedani/taaccct#10]
Need another button that we can link to the OER in the skillscommons.org repository.

**Comment by jkhedani** [comment]
Updated template and markdown to allow for OER repo link 3efdb9b53052109f43cf395a86f00d506b10f295

**Comment by billymeinke** [comment]
Thanks! I updated the modals with links to their project OER on skillscommons. https://github.com/jkhedani/taaccct/commit/f487f12a13c66e0f9c1a8a8c2edb976e21c92afe
