### ISSUE TITLE
about vs. more

### ISSUE THREAD

**Issue by mmmohan** [jkhedani/taaccct#15]
the stuff under "more" i think should be renamed with the label "about" - and i think the current "about" label should be renamed to something else  -  or you can break up the text currently under "about" and move it to the top of the website in the intro, or to other applicable areas.

when i think of what goes in an "about" -- it's more of the background details, partners, links, etc. that is listed under "more" currently

**Comment by billymeinke** [comment]
I moved the sections around to fit inside of the "about" section, and removed the "more" section. https://github.com/jkhedani/taaccct/commit/93b27852caddaee9b36e5c68043727aa9807e7ce

Gave additional context for the microsite and what areas the projects are standouts in.
