### ISSUE TITLE
Create sections in descriptions

### ISSUE THREAD

**Issue by jkhedani** [jkhedani/taaccct#18]
So! I've finally implemented sections in descriptions...for the most part:

![screen shot 2015-01-12 at 10 31 16 pm](https://cloud.githubusercontent.com/assets/1855878/5717835/cb4578e6-9aaa-11e4-9f0b-9c0bd5c629c1.png)

If you look at the markup for "Pathway to Success", you should see how the accordion is being rendered. The reason this "feature" is so complicated to implement is because Jekyll implements strict rules on markdown (which goes against its philosophy, imo.) which aren't defined in any documentation anywhere. So, for the time being as we are inserting content, here are some rules to follow:
1. Don't change the indent on "title" or "section". This kills the Jekyll.
2. Make sure all your titles and content is in double quotes. (e.g. - title: "I'm in double quotes.") Content can often contain a colon which, again, kills the Jekyll.
3. Make sure the content spans one line.  For the time being, it appears that Jekyll attempts to parse carriage returns as another section. This is something I want to fix since it makes editing content extremely difficult.

More rumination:
1. I found it easy to get the text out of double spacing by copy pasta the text into Spotlight then into the doc. All one line.
2. Still working on how to get line breaks for paragraphs without nested lists. If you figure it out, let me know.
3. Still working to get markdown accents and stylings to work. (e.g. bold, italics, etc.)

Will keep a thread going here with updates.

**Comment by billymeinke** [comment]
Thanks for the update!

I was under the impression that posts would be displayed as modals, with the default template pulling and displaying the YAML front matter in the template, and then rendering any markdown-formatted text wherever you insert

{{content}}

into the modal template. That's how it works on the CC Resource Archive:

https://www.dropbox.com/s/tr4xgvy9fsww5ef/Screenshot%202015-01-13%2011.12.12.png?dl=0

Link to file, if it's useful: https://github.com/creativecommons/cc-resource-archive/blob/gh-pages/_layouts/resource.html

Looks like a lot of formatting things break Jekyll. I'll keep wrangling the content, thanks for posting progress on this.

**Comment by jkhedani** [comment]
Correct! (Although I'm not sure where {{ content }} came from. Currently, the post/page object has {{ post.content }} or {{ page.content}} ) But, it seems like the CC resources project uses HTML with Front Matter like such:

![screen shot 2015-01-13 at 5 44 32 pm](https://cloud.githubusercontent.com/assets/1855878/5733725/ec446826-9b4b-11e4-9823-86a2703d8e63.png)

I'd, ideally, like to avoid having to have authors write HTML since in order to get our sectioning to work, we'd have to write markup that looks like this:

![screen shot 2015-01-13 at 5 41 31 pm](https://cloud.githubusercontent.com/assets/1855878/5733732/0c5a432e-9b4c-11e4-9926-8a2519ffb21d.png)

So! I think we have two options at this point:
1. Write our posts with HTML:
   - Get Bootstrap accordion sectioning
   - Have to edit complex HTML in the future
2. Write our posts in Markdown:
   - Ease of editing in markdown and styles enabled
     - Long modal length due to no accordion

Thoughts? @billymeinke

**Comment by billymeinke** [comment]
I'd be OK doing it with HTML, since they probably won't be edited heavily in the future.

Forge ahead! Thanks @jkhedani
