### ISSUE TITLE
"OPEN" logo wrong green color after click

### ISSUE THREAD

**Issue by billymeinke** [jkhedani/taaccct#20]
This is hidden somewhere in the CSS. Would you mind taking a look, @jkhedani?

https://www.dropbox.com/s/j5stkj3xt421yza/Screenshot%202015-02-02%2009.42.36.png?dl=0

**Comment by jkhedani** [comment]
@billymeinke Parent ":focus" attribute in the Bootstrap stylesheet. Removed by making white.
