### ISSUE TITLE
Attributions for Noun Project icons

### ISSUE THREAD

**Issue by billymeinke** [jkhedani/taaccct#21]
Sent you a doc with them inside, @jkhedani. Should try to put these in the footer, no preference on styling from me. Do want to make sure these folks get credit for something that will be seen by lots of folks!

**Comment by jkhedani** [comment]
@billymeinke Updated the footer and moved things around a bit. Let me know if this is good.

**Comment by billymeinke** [comment]
looks great, tweaked it a little and it's done.
