### ISSUE TITLE
Sections in modals not expanding or collapsing

### ISSUE THREAD

**Issue by billymeinke** [jkhedani/taaccct#23]
@jkhedani 

I've included the content from the written pieces, but the accordion text areas are not expanding/contracting in most of the modals. It does work for Air Washington.

Can you take a look? Thx.

**Comment by jkhedani** [comment]
@billymeinke Ah! The issue stems from having too many similar IDs (all IDs should be unique). This bug would be invisible when testing small samples of parsed text as we did. Added a shortened post title as a prefix to the ID which should resolve the issue.
