### ISSUE TITLE
Bill & Melinda Gates logo placement

### ISSUE THREAD

**Issue by janetpkr** [jkhedani/taaccct#5]
Perhaps make text in this horizontal bar smaller so the logo can fit on same line? Or cut some text before Bill & Melinda gates logo (made possible is evident)..

**Comment by billymeinke** [comment]
@janeatcc check out the adjustment I made in the footer. I think this is what you meant. 

Here's the commit: https://github.com/jkhedani/taaccct/commit/fd2a5c0e1feb9d0a889eb0af9069874410786d5d

**Comment by janetpkr** [comment]
Yup
