### ISSUE TITLE
Attributions for Giulia Forsythe

### ISSUE THREAD

**Issue by pgstacey** [jkhedani/taaccct#6]
I recommend we model best practices and generate proper attribution statements (Title, Author, Source, License) for each of Giulia's diagrams which then go below each diagram.

**Comment by billymeinke** [comment]
Agree.

@jkhedani Can this become part of the modal template? I have all the links needed, can insert when the template is ready to receive them.

**Comment by jkhedani** [comment]
Template is ready! 6b08f8d1be433e1152fb32de868ef5608fd6d0c3 The newly allotted fields are:
- img-alt (can serve as title)
- img-author (Giulia Forsythe)
- img-license (e.g. Creative Commons Attribution 4.0 International License.)

Let me know if other fields are needed. Merging [this](https://github.com/jkhedani/taaccct/issues/16) issue here.

**Comment by billymeinke** [comment]
Yeah, it'd be ideal to use CCREL metadata in the attribution.

The chooser can show you which fields to include, and will spit out HTML that could be included in the modal template, I think:

http://creativecommons.org/choose/

At minimum, we need a link back to the license. Better would be to include a list of links to these infographics hosted on Flickr inside the attribution. I can get you the list if you think it'd be simple to implement, @jkhedani

**Comment by jkhedani** [comment]
Added. Please see final commit.
