### ISSUE TITLE
White Space

### ISSUE THREAD

**Issue by pgstacey** [jkhedani/taaccct#8]
Clicking Projects, About, More at top right takes you to appropriate section but the black letters of the section Title touch the black bar across the top. Would be better if there were a bit of white space between the two.

**Comment by billymeinke** [comment]
Agree. Need an additional line break or just more space above the top of the sections.

**Comment by billymeinke** [comment]
@pgstacey 

I added some space, please take another look.

https://github.com/jkhedani/taaccct/commit/592a12249ad06c61259948901a0d49b8fc23ac13
