### ISSUE TITLE
Center align icons in industry section

### ISSUE THREAD

**Issue by billymeinke** [jkhedani/taaccct#9]
Healthcare aligns left, need to offset or align to the middle.

https://www.dropbox.com/s/l3n0nn4pcn2du2q/Screenshot%202015-01-08%2011.40.30.png?dl=0

**Comment by jkhedani** [comment]
![screen shot 2015-01-10 at 10 24 33 am](https://cloud.githubusercontent.com/assets/1855878/5693115/1de30be4-98b3-11e4-9f94-1f7f89660f17.png)

How about we do a five up like this? `15cee6`

**Comment by billymeinke** [comment]
Yep, that looks great to me. Thanks @jkhedani
